#!/usr/bin/bash
container_name=${1:-stable_pose_aae}
xhost +local:docker 

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
touch $XAUTH
if [ ! -f $XAUTH ]
then
    xauth_list=$(xauth nlist :0 | sed -e 's/^..../ffff/')
    if [ ! -z "$xauth_list" ]
    then
        echo $xauth_list | xauth -f $XAUTH nmerge -
    else
        touch $XAUTH
    fi
    chmod a+r $XAUTH
fi

wandb docker-run -it \
	--name $container_name \
	--volume=$XSOCK:$XSOCK:rw \
        --volume=$XAUTH:$XAUTH:rw \
        --volume=/dev:/dev \
        --privileged \
	--volume=$PWD:/cobot_aae \
	--env="XAUTHORITY=$XAUTH" \
	--env="DISPLAY=$DISPLAY" \
	--env="QT_X11_NO_MITSHM=1" \
	--runtime=nvidia \
	--net=host --gpus all \
	--env="NVIDIA_DRIVER_CAPABILITIES=all" \
    $container_name
	bash
